apiVersion: v1
kind: Service
metadata:
  name: product-catalog-service
spec:
  selector:
    app: product-catalog-service
  ports:
  - name: http
    port: 80
    targetPort: 5000
  type: LoadBalancer

